#if defined __GNUC__ && defined COVERAGE
#define AUTD3_API __attribute__((__used__))
#else
#define AUTD3_API
#endif

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::native_methods {

extern "C" {

AUTD3_API
AUTD3_API [[nodiscard]] ResultModulation AUTDModulationWav(const char *path, SamplingConfiguration config, LoopBehavior loop_behavior);

AUTD3_API [[nodiscard]] bool AUTDModulationWavIsDefault(ModulationPtr wav);

AUTD3_API
AUTD3_API [[nodiscard]] ResultModulation AUTDModulationRawPCM(const char *path, uint32_t sample_rate, SamplingConfiguration config,
                                                              LoopBehavior loop_behavior);

AUTD3_API [[nodiscard]] bool AUTDModulationRawPCMIsDefault(ModulationPtr rawpcm);

}  // extern "C"

}  // namespace autd3::native_methods
