#if defined __GNUC__ && defined COVERAGE
#define AUTD3_API __attribute__((__used__))
#else
#define AUTD3_API
#endif

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::native_methods {

enum class Backend : uint8_t {
  Plotters = 0,
  Python = 1,
  Null = 2,
};

enum class CMap : uint8_t {
  Jet = 0,
  Viridis = 1,
  Magma = 2,
  Inferno = 3,
  Plasma = 4,
  Cividis = 5,
  Turbo = 6,
  Circle = 7,
  Bluered = 8,
  Breeze = 9,
  Mist = 10,
  Earth = 11,
  Hell = 12,
};

enum class Directivity : uint8_t {
  Sphere = 0,
  T4010A1 = 1,
};

struct PlotRangePtr {
  void *_0;
};

struct ConfigPtr {
  void *_0;
};

struct NullPlotConfigPtr {
  void *_0;
};

struct PlotConfigPtr {
  void *_0;
};

struct ResultPlotConfig {
  PlotConfigPtr result;
  uint32_t err_len;
  void *err;
};

struct PyPlotConfigPtr {
  void *_0;
};

struct ResultPyPlotConfig {
  PyPlotConfigPtr result;
  uint32_t err_len;
  void *err;
};

extern "C" {

AUTD3_API
AUTD3_API [[nodiscard]] PlotRangePtr AUTDLinkVisualizerPlotRange(double x_min, double x_max, double y_min, double y_max, double z_min, double z_max,
                                                                 double resolution);

AUTD3_API [[nodiscard]] uint64_t AUTDLinkVisualizerPlotRangeObservePointsLen(PlotRangePtr range);

AUTD3_API void AUTDLinkVisualizerPlotRangeObservePoints(PlotRangePtr range, double *points);

AUTD3_API
uint32_t AUTDLinkVisualizerPhasesOf(LinkPtr visualizer, Backend backend, Directivity directivity, Segment segment, uint32_t idx, uint8_t *buf);

AUTD3_API
uint32_t AUTDLinkVisualizerIntensities(LinkPtr visualizer, Backend backend, Directivity directivity, Segment segment, uint32_t idx, uint8_t *buf);

AUTD3_API
uint32_t AUTDLinkVisualizerModulation(LinkPtr visualizer, Backend backend, Directivity directivity, Segment segment, uint8_t *buf);

AUTD3_API
ResultI32 AUTDLinkVisualizerCalcField(LinkPtr visualizer, Backend backend, Directivity directivity, const double *points, uint32_t points_len,
                                      GeometryPtr geometry, Segment segment, uint32_t idx, double *buf);

AUTD3_API
AUTD3_API [[nodiscard]] ResultI32 AUTDLinkVisualizerPlotField(LinkPtr visualizer, Backend backend, Directivity directivity, ConfigPtr config,
                                                              PlotRangePtr range, GeometryPtr geometry, Segment segment, uint32_t idx);

AUTD3_API
AUTD3_API [[nodiscard]] ResultI32 AUTDLinkVisualizerPlotPhase(LinkPtr visualizer, Backend backend, Directivity directivity, ConfigPtr config,
                                                              GeometryPtr geometry, Segment segment, uint32_t idx);

AUTD3_API
AUTD3_API [[nodiscard]] ResultI32 AUTDLinkVisualizerPlotModulation(LinkPtr visualizer, Backend backend, Directivity directivity, ConfigPtr config,
                                                                   Segment segment);

AUTD3_API [[nodiscard]] LinkBuilderPtr AUTDLinkVisualizerSphereNull(bool use_gpu, int32_t gpu_idx);

AUTD3_API [[nodiscard]] LinkBuilderPtr AUTDLinkVisualizerT4010A1Null(bool use_gpu, int32_t gpu_idx);

AUTD3_API [[nodiscard]] NullPlotConfigPtr AUTDLinkVisualizerNullPlotConfig();

AUTD3_API
AUTD3_API [[nodiscard]] LinkBuilderPtr AUTDLinkVisualizerSpherePlotters(bool use_gpu, int32_t gpu_idx);

AUTD3_API
AUTD3_API [[nodiscard]] LinkBuilderPtr AUTDLinkVisualizerT4010A1Plotters(bool use_gpu, int32_t gpu_idx);

AUTD3_API
AUTD3_API [[nodiscard]] ResultPlotConfig AUTDLinkVisualizerPlotConfig(uint32_t width, uint32_t height, double cbar_size, uint32_t font_size,
                                                                      uint32_t label_area_size, uint32_t margin, double ticks_step, CMap cmap,
                                                                      const char *fname);

AUTD3_API [[nodiscard]] bool AUTDLinkVisualizerPlotConfigIsDefault(PlotConfigPtr config);

AUTD3_API
AUTD3_API [[nodiscard]] LinkBuilderPtr AUTDLinkVisualizerSpherePython(bool use_gpu, int32_t gpu_idx);

AUTD3_API
AUTD3_API [[nodiscard]] LinkBuilderPtr AUTDLinkVisualizerT4010A1Python(bool use_gpu, int32_t gpu_idx);

AUTD3_API
AUTD3_API [[nodiscard]] ResultPyPlotConfig AUTDLinkVisualizerPyPlotConfig(int32_t width, int32_t height, int32_t dpi, const char *cbar_position,
                                                                          const char *cbar_size, const char *cbar_pad, int32_t fontsize,
                                                                          double ticks_step, const char *cmap, bool show, const char *fname);

AUTD3_API [[nodiscard]] bool AUTDLinkVisualizerPyPlotConfigIsDefault(PyPlotConfigPtr config);

}  // extern "C"

}  // namespace autd3::native_methods
