#if defined __GNUC__ && defined COVERAGE
#define AUTD3_API __attribute__((__used__))
#else
#define AUTD3_API
#endif

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::native_methods {

struct LinkSimulatorBuilderPtr {
  void* _0;
};

struct ResultLinkSimulatorBuilder {
  LinkSimulatorBuilderPtr result;
  uint32_t err_len;
  void* err;
};

extern "C" {

AUTD3_API [[nodiscard]] LinkSimulatorBuilderPtr AUTDLinkSimulator(uint16_t port);

AUTD3_API
AUTD3_API [[nodiscard]] ResultLinkSimulatorBuilder AUTDLinkSimulatorWithAddr(LinkSimulatorBuilderPtr simulator, const char* addr);

AUTD3_API
AUTD3_API [[nodiscard]] LinkSimulatorBuilderPtr AUTDLinkSimulatorWithTimeout(LinkSimulatorBuilderPtr simulator, uint64_t timeout_ns);

AUTD3_API
AUTD3_API [[nodiscard]] LinkBuilderPtr AUTDLinkSimulatorIntoBuilder(LinkSimulatorBuilderPtr simulator);

AUTD3_API
AUTD3_API [[nodiscard]] ResultI32 AUTDLinkSimulatorUpdateGeometry(LinkPtr simulator, GeometryPtr geometry);

}  // extern "C"

}  // namespace autd3::native_methods
